### ISSUE TITLE
Some URLs fail to parse

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#103]
ok so first up im sorry that most of the bugs I find are with porn sites but youtube just works and theres so many more variables and things to go wrong with porn its easier to find broken things lol....

when attempting to download the following video:

**Comment by CountParadox** [comment]
I have tried stripping the tailing parts of the URL off leaving just the video ID but it doesnt help.

**Comment by CountParadox** [comment]
`
2020-05-25T23:04:07.227Z ERROR: ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.,
2020-05-25T23:04:06.722Z ERROR: failed to parse for urls starting with http://www.91porn.com/view_video.php?viewkey=c7d1a52892d3cf1a30fe&page=&viewtype=&category=,
2020-05-25T23:04:06.721Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -- http://www.91porn.com/view_video.php?viewkey=c7d1a52892d3cf1a30fe&page=&viewtype=&category=,
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o users/admin/video/%(title)s.mp4 -f best[ext=mp4] --write-info-json --print-json --restrict-filenames -- https://www.xvideos.com/video54265939/15841175/0/transparent_dress_in_public,
2020-05-25T23:13:16.107Z ERROR: ERROR: unable to rename file: [Errno 2] No such file or directory,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4),
    at makeError (/app/node_modules/execa/lib/error.js:56:11),
    at handlePromise (/app/node_modules/execa/index.js:114:26),
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o users/admin/video/%(title)s.mp4 -f best[ext=mp4] --write-info-json --print-json --restrict-filenames -- http://www.91porn.com/view_video.php?viewkey=a72c1e2c020798a27c3b&page=&viewtype=&category=,
2020-05-25T23:06:29.280Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -- http://www.91porn.com/view_video.php?viewkey=a72c1e2c020798a27c3b&page=&viewtype=&category=,
2020-05-25T23:06:29.281Z ERROR: failed to parse for urls starting with http://www.91porn.com/view_video.php?viewkey=a72c1e2c020798a27c3b&page=&viewtype=&category=,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at runMicrotasks (<anonymous>),
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o users/admin/video/%(title)s.mp4 -f best[ext=mp4] --write-info-json --print-json --restrict-filenames -- http://www.91porn.com/view_video.php?viewkey=c7d1a52892d3cf1a30fe&page=&viewtype=&category=,
2020-05-25T23:06:29.463Z ERROR: ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)`

**Comment by SuperSandro2000** [comment]
Can you please use triple ` for long logs or gist, pastebin, etc.?

**Comment by Tzahi12345** [comment]
@SuperSandro2000 Added!

I'm getting the same error on my end, I think this is (unfortunately) a problem on youtube-dl's end and not something I can fix. I tried adding the `--restrict-filenames` arg, but it didn't seem to help.

I would recommend opening up an issue [here](https://github.com/ytdl-org/youtube-dl). Before doing that, I would run the command on youtube-dl itself and copy the logs from there (you don't want to mix my logs with youtube-dl's logs). Reason I say that is they are very particular about issues, and including erroneous logs might set them off, who knows :P

You can post the link here so we can follow it. I'll keep this open in case you or anyone else finds a workaround.

Also, don't feel about about including porn sites, it's good to test this app with obscure sites to make it more compatible across the board (which is something I want). So keep it up!
