### ISSUE TITLE
[BUG] Failure to start with Docker image

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#1060]
**Describe the bug**
An error occurs within a few minutes of starting Docker and continues to restart afterward.
I don't know why the error occurs.

**Environment**
tzahi12345/youtubedl-material:nightly

os version
proxmox -> ubuntu 23.04 -> rclone mount <-> synology nas webdav share
`
Linux version 6.2.0-39-generic (buildd@bos03-amd64-014) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.40) #40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023
`

**Additional context**
docker log
```
2023-12-20T09:00:07.767Z INFO: Config items set using ENV variables.
2023-12-20T09:00:07.898Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:00:08.206Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:00:08.932Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:00:12.779Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:00:12.790Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:01:05.904Z INFO: Config items set using ENV variables.
2023-12-20T09:01:06.032Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:01:06.300Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:01:07.064Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:01:09.411Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:01:09.427Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:02:09.657Z INFO: Config items set using ENV variables.
2023-12-20T09:02:09.787Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:02:10.081Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:02:12.013Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:02:12.020Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:02:12.027Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:03:05.899Z INFO: Config items set using ENV variables.
2023-12-20T09:03:06.027Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:03:06.303Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:03:07.060Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:03:12.427Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:03:12.440Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:04:06.545Z INFO: Config items set using ENV variables.
2023-12-20T09:04:06.673Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:04:06.975Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:04:07.705Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:04:13.595Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:04:13.611Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:05:05.853Z INFO: Config items set using ENV variables.
2023-12-20T09:05:05.982Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:05:06.263Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:05:07.022Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:05:09.014Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:05:09.028Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:06:10.147Z INFO: Config items set using ENV variables.
2023-12-20T09:06:10.276Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:06:10.593Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:06:11.310Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:06:13.646Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:06:13.660Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:07:06.031Z INFO: Config items set using ENV variables.
2023-12-20T09:07:06.160Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:07:06.447Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:07:07.197Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:07:12.745Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
2023-12-20T09:07:12.758Z VERBOSE: Subscription: getting list of videos to download for tk7 with args: --dump-json,-o,"subscriptions/playlists/tk7/%(upload_date)s_%(title).220B.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--cookies,appdata/cookies.txt,--write-thumbnail,-r,8000k,--no-clean-info-json
2023-12-20T09:08:06.696Z INFO: Config items set using ENV variables.
2023-12-20T09:08:06.825Z WARN: Failed to get youtube-dl binary details at location 'appdata/youtube-dl.json'. Generating file...
2023-12-20T09:08:07.168Z WARN: Updating yt-dlp binary to 'appdata/bin/yt-dlp', downloading...
2023-12-20T09:08:07.859Z VERBOSE: Disabling checking downloads as none are available.
2023-12-20T09:08:09.479Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442

```

node log 1
```
0 verbose cli [
0 verbose cli   '/usr/local/nvm/versions/node/v16.14.2/bin/node',
0 verbose cli   '/usr/local/nvm/versions/node/v16.14.2/bin/npm',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/nvm/versions/node/v16.14.2/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/app/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/youtube/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/nvm/versions/node/v16.14.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 2ms
23 verbose logfile /app/.npm/_logs/2023-12-20T18_45_05_213Z-debug-0.log
24 timing npm:load:logFile Completed in 3ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 18ms
28 silly logfile start cleaning logs, removing 1 files
29 timing command:run-script Completed in 56686ms
30 timing command:start Completed in 56688ms
31 verbose stack Error: command failed
31 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
31 verbose stack     at ChildProcess.emit (node:events:526:28)
31 verbose stack     at maybeClose (node:internal/child_process:1092:16)
31 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
32 verbose pkgid backend@1.0.0
33 verbose cwd /app
34 verbose Linux 6.2.0-39-generic
35 verbose argv "/usr/local/nvm/versions/node/v16.14.2/bin/node" "/usr/local/nvm/versions/node/v16.14.2/bin/npm" "start"
36 verbose node v16.14.2
37 verbose npm  v8.5.0
38 error path /app
39 error command failed
40 error signal SIGTERM
41 error command sh -c pm2-runtime --raw pm2.config.js
42 verbose exit 1
43 timing npm Completed in 56796ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /app/.npm/_logs/2023-12-20T18_45_05_213Z-debug-0.log
```
node log 2
```
0 verbose cli [
0 verbose cli   '/usr/local/nvm/versions/node/v16.14.2/bin/node',
0 verbose cli   '/usr/local/nvm/versions/node/v16.14.2/bin/npm',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/nvm/versions/node/v16.14.2/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/app/.npmrc Completed in 0ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:/home/youtube/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/nvm/versions/node/v16.14.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile /app/.npm/_logs/2023-12-20T18_46_04_880Z-debug-0.log
24 timing npm:load:logFile Completed in 3ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 19ms
28 silly logfile start cleaning logs, removing 1 files
29 timing command:run-script Completed in 56578ms
30 timing command:start Completed in 56580ms
31 verbose stack Error: command failed
31 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
31 verbose stack     at ChildProcess.emit (node:events:526:28)
31 verbose stack     at maybeClose (node:internal/child_process:1092:16)
31 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
32 verbose pkgid backend@1.0.0
33 verbose cwd /app
34 verbose Linux 6.2.0-39-generic
35 verbose argv "/usr/local/nvm/versions/node/v16.14.2/bin/node" "/usr/local/nvm/versions/node/v16.14.2/bin/npm" "start"
36 verbose node v16.14.2
37 verbose npm  v8.5.0
38 error path /app
39 error command failed
40 error signal SIGTERM
41 error command sh -c pm2-runtime --raw pm2.config.js
42 verbose exit 1
43 timing npm Completed in 56690ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /app/.npm/_logs/2023-12-20T18_46_04_880Z-debug-0.log
```
All logs seem to be the same.

**Comment by martadinata666** [comment]
That is the log from ` error     /app/.npm/_logs/2023-12-20T18_46_04_880Z-debug-0.log`? Complete log?

And how your deployment. Any issue on other part? Like the MongoDB?

**Comment by arithxp** [comment]
> That is the log from ` error /app/.npm/_logs/2023-12-20T18_46_04_880Z-debug-0.log`? Complete log? And how your deployment is. Do you have any issues on the other part? The MongoDB?
> 
> I had two sus.
> 
>     1. Is the data directory you mounting somehow incompatible?
> 
>     2. The VM setting of CPU, is missing CPU instructions.

There were several logs, and they all had the same content, just different times.
[logs.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/13734234/logs.zip)

I don't think there is a problem with vm settings or mounting.
Because there was no problem with the image from a few months ago.
When tested using the tzahi12345/youtubedl-material:nightly-2023-08-29 image, it works without any major problems.

**Comment by martadinata666** [comment]
There is no error exit code from docker? do simple `docker compose up`.

**Comment by arithxp** [comment]
> There is no error exit code from docker? do simple `docker compose up`.
> 
> and `cat /proc/cpuinfo`

docker-compose up
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/6009737/2a301bb7-e59d-4086-9be4-43bc2eeca4d4)
[logs.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/13737129/logs.zip)




cat /proc/cpuinfo
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 96
model name      : AMD Ryzen 5 PRO 4650G with Radeon Graphics
stepping        : 1
microcode       : 0x8600109
cpu MHz         : 3693.046
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips        : 7386.09
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 96
model name      : AMD Ryzen 5 PRO 4650G with Radeon Graphics
stepping        : 1
microcode       : 0x8600109
cpu MHz         : 3693.046
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips        : 7386.09
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 96
model name      : AMD Ryzen 5 PRO 4650G with Radeon Graphics
stepping        : 1
microcode       : 0x8600109
cpu MHz         : 3693.046
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips        : 7386.09
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 96
model name      : AMD Ryzen 5 PRO 4650G with Radeon Graphics
stepping        : 1
microcode       : 0x8600109
cpu MHz         : 3693.046
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips        : 7386.09
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:
```

**Comment by martadinata666** [comment]
That is the cpu from VM? If it so, then kinda hard to tell whats going on. It realibly replicated.

**Comment by arithxp** [comment]
> That is the cpu from VM? If it so, then kinda hard to tell whats going on. It hard to be realibly replicated.

yes. Proxmox can set the CPU Host mode.
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/6009737/e573075e-de3d-4908-9284-b764a50018d9)

I don't know why this happens.
I looked at the Issue, but sadly, it seems to happen to me.

Anyway, thank you for checking.

**Comment by arithxp** [comment]
> So from the logs it crashing when checking subs, is clean state deployment got same issue?

I don't know why, but an error occurs if the Docker volume is mounted.
If I start without a mount, no error occurs.
