### ISSUE TITLE
[BUG] Skipping player responses from android clients

### ISSUE THREAD

**Issue by upuldi** [Tzahi12345/YoutubeDL-Material#1113]
I am getting the following error when trying to download Youtube videos.
23/04/202414:57:03
2024-04-23T04:57:03.736Z INFO: YoutubeDL-Material v4.3.2 started on PORT 17442
23/04/202415:02:02
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:02
    at /app/downloader.js:635:39
23/04/202415:02:02
    at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:187:14)
23/04/202415:02:03
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:03
    at /app/downloader.js:635:39
23/04/202415:02:03
    at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:187:14)
23/04/202415:02:03
    at FSReqCallback.oncomplete (node:fs:188:23)
23/04/202415:02:04
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:04
    at /app/downloader.js:635:39
23/04/202415:02:04
    at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:187:14)
23/04/202415:02:04
    at FSReqCallback.oncomplete (node:fs:188:23)
23/04/202415:02:05
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:05
    at /app/downloader.js:635:39
23/04/202415:02:05
    at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:187:14)
23/04/202415:02:05
    at FSReqCallback.oncomplete (node:fs:188:23)
23/04/202415:02:06
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:06
    at /app/downloader.js:635:39
23/04/202415:02:06
    at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:187:14)
23/04/202415:02:06
    at FSReqCallback.oncomplete (node:fs:188:23)
23/04/202415:02:07
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:07
    at /app/downloader.js:635:39
23/04/202415:02:07
    at FSReqCallback.oncomplete (node:fs:188:23)
23/04/202415:02:08
TypeError: Cannot read properties of undefined (reading 'length')
23/04/202415:02:08
    at /app/downloader.js:635:39
23/04/202415:02:08
    at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:187:14)
23/04/202415:02:08
    at FSReqCallback.oncomplete (node:fs:188:23)
23/04/202415:02:08
2024-04-23T05:02:08.955Z ERROR: WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "b3Q9o3APTsQ")
23/04/202415:02:08
ERROR: [Errno 13] Permission denied: 'video/1 Tablespoon a Day Burns Belly Fat and Keeps Clogged Arteries Away ｜ Dr Mandell.webp'

**Comment by Snogard** [comment]
it is a yt-dlp [issue](https://github.com/yt-dlp/yt-dlp/issues/9554)
