### ISSUE TITLE
Error during parsing, unable to extract title

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#133]
another one for you, 

logs below:

```

(node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o users/admin/video/%(title)s.mp4 -f best[ext=mp4] --write-info-json --print-json --restrict-filenames -- http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc,
    at makeError (/app/node_modules/execa/lib/error.js:56:11),
    at handlePromise (/app/node_modules/execa/index.js:114:26),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1),
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
2020-06-14T04:54:27.262Z ERROR: ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.,
2020-06-14T04:54:26.365Z ERROR: failed to parse for urls starting with http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7),
2020-06-14T04:53:52.905Z INFO: YoutubeDL-Material v4.0 started on PORT 443,
2020-06-14T04:54:26.363Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -- http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc,
    at runMicrotasks (<anonymous>),
2020-06-14T04:53:11.928Z ERROR: ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6),
2020-06-14T04:53:11.350Z ERROR: failed to parse for urls starting with http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc,
2020-06-14T04:53:11.349Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -- http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5),
2020-06-14T04:52:40.555Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -- http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc&page=&viewtype=&category=,
2020-06-14T04:52:40.556Z ERROR: failed to parse for urls starting with http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc&page=&viewtype=&category=,
2020-06-14T04:52:41.173Z ERROR: ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.,
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o users/admin/video/%(title)s.mp4 -f best[ext=mp4] --write-info-json --print-json --restrict-filenames -- http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc&page=&viewtype=&category=

```

Happens for this video::

[http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc](http://www.91porn.com/view_video.php?viewkey=1a0559e8b72a87992dbc)

I suspected it may be due to the url having additional arguments (it had &category=blah) etc but stripping those did not help.

I am running **

tzahi12345/youtubedl-material:nightly@sha256:4e2efbb9a28e1bc567158947b7272b1a64979101c25cf8706be8f27a0b4d577c
--

**

**Comment by Tzahi12345** [comment]
Sorry for the delay responding! I see there's [a PR for youtube-dl](https://github.com/ytdl-org/youtube-dl/pull/25842) which will supposedly fix this. Once that happens, you can restart your instance to update youtube-dl.

Let me know if you run into downloading problems outside this issue!

**Comment by CountParadox** [comment]
[youtube-dl.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/4985401/youtube-dl.zip)
compiled binary of latest version of youtube-dl as of 28-7-2020 with 91porn title fix changes manually merged for any interested.

**Comment by Tzahi12345** [comment]
Wow awesome work!

**Comment by CountParadox** [comment]
Hey @Tzahi12345  now that ive got things running again, can you give me a pointer how I can use my custom build here in the docker version? :D

**Comment by Tzahi12345** [comment]
You have to place your custom binary in this folder in the container: `app/backend/node_modules/youtube-dl/bin`

Let me know if you need help doing this!

**Comment by CountParadox** [comment]
I cant seem to exec into the container :/ 

`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown`
