### ISSUE TITLE
Subscribe to private playlist, not possible with cookie?

### ISSUE THREAD

**Issue by Logimann** [Tzahi12345/YoutubeDL-Material#183]
Hello,
i try to save my privat favorite playlist but unfortunately this does not work with the subscribe function.

If I insert this playlist on the start page this works, as well as other private videos. So the cookie works.
```
(node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null

    at validateString (internal/validators.js:120:11)

    at Object.join (path.js:1039:7)

    at getAppendedBasePath (/app/subscriptions.js:431:17)

    at /app/subscriptions.js:161:34

    at new Promise (<anonymous>)

    at Object.unsubscribe (/app/subscriptions.js:147:12)

    at /app/app.js:2204:40

    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

    at next (/app/node_modules/express/lib/router/route.js:137:13)

    at complete (/app/node_modules/passport/lib/middleware/authenticate.js:268:13)

    at /app/node_modules/passport/lib/middleware/authenticate.js:275:15

    at pass (/app/node_modules/passport/lib/authenticator.js:431:14)

    at Authenticator.transformAuthInfo (/app/node_modules/passport/lib/authenticator.js:453:5)

    at /app/node_modules/passport/lib/middleware/authenticate.js:272:22

    at IncomingMessage.req.login.req.logIn (/app/node_modules/passport/lib/http/request.js:55:13)

    at JwtStrategy.strategy.success (/app/node_modules/passport/lib/middleware/authenticate.js:253:13)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

2020-07-31T17:18:07.882Z ERROR: ERROR: This playlist is private, use --username or --netrc to access it.

2020-07-31T17:18:07.883Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.
```

I've already tried everything I can think of. Even setting user-defined args. I figured out the command for path cookies is. `--cookies,appdata/cookies.txt`

It runs in a docker container with version 4.1 according to gui, but according to cli 4.0 I suppose this is only a typo.

Thank you very much in advance, I really don't know what else to do.

**Comment by Tzahi12345** [comment]
>It runs in a docker container with version 4.1 according to gui, but according to cli 4.0 I suppose this is only a typo.

Definitely a typo, are you on the `4.1` tag or the `latest` tag?

Anyways, you did find a bug here! Basically, before a subscription's videos are retrieved, we first get some metadata like the name and create the needed directories. After that's done, the videos are retrieved. During the metadata retrieval step, the cookies weren't being used, which resulted in the subscription failing.

I went ahead and fixed the problem, you can see the [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/057ad67672104c07f25e223692a968e630b248de). You can get this fix immediately by using the `nightly` tag on Docker. Let me know if you run into any other issues!
