### ISSUE TITLE
Unable to write to /.cache

### ISSUE THREAD

**Issue by DarkSkyGhost** [Tzahi12345/YoutubeDL-Material#270]
Running latest nightly inside a Docker container on Synology.

Material is able to download videos and write to target directories.

Stacktrace:

> 2020-11-26T05:48:38.619Z ERROR: WARNING: Writing cache to u'/.cache/youtube-dl/youtube-sigfuncs/js_77da52cd_109.json' failed: Traceback (most recent call last):
File "/app/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/cache.py", line 49, in store
os.makedirs(os.path.dirname(fn))
File "/usr/lib/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/.cache'
WARNING: Writing cache to u'/.cache/youtube-dl/youtube-sigfuncs/js_77da52cd_105.json' failed: Traceback (most recent call last):
File "/app/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/cache.py", line 49, in store
os.makedirs(os.path.dirname(fn))
File "/usr/lib/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/.cache'

**Comment by Tzahi12345** [comment]
To clarify what's going on: the videos download just fine, you just get this annoying error/warning every time you download?

**Comment by DarkSkyGhost** [comment]
Yes, exactly.

Not sure what else breaks with with this.

**Comment by ar-jan** [comment]
Same issue here, using Docker.

**Comment by CaCTuCaTu4ECKuu** [comment]
Error is still there.
Not sure relative to what './cache' folder is, but I could've create it myself and give permissions needed.
I must've been folder inside container that you dont have to care about or should have volume defied 

```
WARNING: Writing cache to '/.cache/yt-dlp/youtube-nsig/074a8365.json' failed: Traceback (most recent call last):
File "/app/appdata/bin/yt-dlp/yt_dlp/cache.py", line 41, in store
os.makedirs(os.path.dirname(fn), exist_ok=True)
File "/usr/lib/python3.10/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.10/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.10/os.py", line 225, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```

Using docker under Truenas Scale
> Version: v4.3.2
> Docker tag: nightly
> Commit hash: 58f4313
> Build date: 2025-02-04

**Comment by EyePulp** [comment]
FWIW I was able to fix this under docker compose by mapping a volume. The host paths are what I'm using on a synology machine -- adjust as needed. I also manually created the .cache folder in the host machine.

- /volume1/docker/apps/youtube/appdata:/appdata
- /volume1/docker/apps/youtube/appdata/.cache:/.cache
