### ISSUE TITLE
Docker container crashing while starting a download

### ISSUE THREAD

**Issue by partymild** [Tzahi12345/YoutubeDL-Material#276]
Since sometimes this week my docker container crashes everytime after I input an url and click 'download'
I've got the following error in my logs:

2020-12-03T16:26:58.134Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f best[ext=mp4],--cookies,appdata/cookies.txt,--download-archive,video/merged_video.txt,--sleep-interval 15
(node:1) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: Unknown system error -122: Unknown system error -122, write
Emitted 'error' event on WriteStream instance at:
    at WriteStream.onerror (/app/node_modules/multistream/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at WriteStream.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/fs/streams.js:409:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:608:5) {
  errno: -122,
  code: 'Unknown system error -122',
  syscall: 'write'
}

**Comment by Tzahi12345** [comment]
What's the video if you don't mind sharing? Maybe the file is too large, though I've never seen this error before. All I could find is [this issue on the npm cli repo](https://github.com/npm/npm/issues/16604#issuecomment-302550401)

**Comment by partymild** [comment]
It seems like the error was on my side.. I've checked everything but the quota of the shared folder - which was full.. disregard this error :/

**Comment by partymild** [comment]
But now there's a new one:


2020-12-07T10:31:54.280Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f best[ext=mp4],--cookies,appdata/cookies.txt,--download-archive,video/merged_video.txt,--sleep-interval 15 


2020-12-07T10:31:57.620Z ERROR: Command failed with exit code 2: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -o video/%(title)s.mp4 --write-info-json --print-json -f best[ext=mp4] --cookies appdata/cookies.txt --download-archive video/merged_video.txt --sleep-interval 15 http://www.youtube.com/watch?v=-GALBxoPytg

**Comment by partymild** [comment]
Downloads via Subscriptions work fine though.. so let me know if/what additional infos you need.

**Comment by Tzahi12345** [comment]
It could be that your cookies are outdated, you may want to try downloading without that. Or, perhaps `--sleep-interval 15` is causing issues as well.

Also verify that you're separating your custom args by `,,` to make sure they are read properly by the app.

**Comment by gerroon** [comment]
I have this issue too, it seems like it crashes randomly sometimes, not always, the ui works but the downloader does not. All I have is this in the docker-compose logs. 

`youtubedl-material_ytdl_material_1 exited with code 1` 

If you can tell me how to get better logs I can provide it here

**Comment by Tzahi12345** [comment]
Hm that's strange, is there usually something that happens before it crashes, such as downloading a video? Or is it completely random?

**Comment by gerroon** [comment]
I cant tell because it seems to happen at night when I was not downloading anything.

**Comment by partymild** [comment]
> It could be that your cookies are outdated, you may want to try downloading without that. Or, perhaps `--sleep-interval 15` is causing issues as well.
> 
> Also verify that you're separating your custom args by `,,` to make sure they are read properly by the app.

`--sleep-interval 15` was causing the problem, after removing it it's working again - thank you!
my issues are solved now.

**Comment by Tzahi12345** [comment]
Good to hear it's fixed, I'll go ahead and close the issue!
