### ISSUE TITLE
ERROR: Command failed with exit code 1

### ISSUE THREAD

**Issue by gerroon** [Tzahi12345/YoutubeDL-Material#283]
Trying to download a video and getting this error. I am using docker-compose This generally works not sure why i get these kinds of errors sometimes.

```
ytdl_material_1  | 2020-12-13T04:07:22.264Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f best[ext=mp4]
ytdl_material_1  | 2020-12-13T04:07:29.450Z ERROR: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -o video/%(title)s.mp4 --write-info-json --print-json -f best[ext=mp4] http://www.youtube.com/watch?v=nuPPNKx9YuY

```

**Comment by Tzahi12345** [comment]
Can you switch the tag to `nightly` and try again? `-f best[ext=mp4]` were the args before but in the new version it's `-f,bestvideo+bestaudio`, the added comma in between may have fixed this.

**Comment by gerroon** [comment]
It is either not downloading or partially downloads, like `.f137.mp4.part`


```
ytdl_material_1  | 2020-12-13T18:39:09.203Z WARN: Cannot find config with key 'ytdl_default_downloader'. Creating one with the default value...
ytdl_material_1  | 2020-12-13T18:39:09.205Z WARN: Cannot find config with key 'ytdl_jwt_expiration'. Creating one with the default value...
ytdl_material_1  | 2020-12-13T18:39:11.051Z INFO: youtube-dl successfully updated!
ytdl_material_1  | 2020-12-13T18:39:11.057Z INFO: YoutubeDL-Material v4.1 started on PORT 17442
ytdl_material_1  | 2020-12-13T19:13:12.363Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
ytdl_material_1  | 2020-12-13T19:13:20.010Z WARN: Categories could not be found. Initializing categories...
ytdl_material_1  | 2020-12-13T19:13:27.152Z ERROR: ERROR: Unable to download webpage: <urlopen error [Errno 99] Address not available> (caused by URLError(error(99, 'Address not available'),))
ytdl_material_1  | 2020-12-13T19:13:40.478Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
ytdl_material_1  | 2020-12-13T19:14:11.193Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
ytdl_material_1  | 2020-12-13T19:14:33.189Z ERROR: ERROR: unable to download video data: <urlopen error [Errno -3] Try again>

```

**Comment by Tzahi12345** [comment]
What is the video you're trying to download?

The `<urlopen error [Errno 99] Address not available>` is what I get when I reset my connection halfway through downloading. Perhaps this is a internet connection issue or maybe the video is unavailable for some odd reason.

**Comment by gerroon** [comment]
Maybe ?

```
ytdl_material_1  | (node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl -o video/%(title)s.mp4 --write-info-json --print-json -- http://10.2.0.10:3053/#dhcp
ytdl_material_1  |     at makeError (/app/node_modules/execa/lib/error.js:56:11)
ytdl_material_1  |     at handlePromise (/app/node_modules/execa/index.js:114:26)
ytdl_material_1  |     at runMicrotasks (<anonymous>)
ytdl_material_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ytdl_material_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
ytdl_material_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```
