### ISSUE TITLE
[BUG] Failed pre-check for video info error

### ISSUE THREAD

**Issue by u0a** [Tzahi12345/YoutubeDL-Material#449]
Hi, I'm using YoutubeDL-Material with Synology Docker, and there is a problem with download.
When I enter youtube link to download the video, it fails.

Failed pre-check for video info: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=qo7ae99w1IQ

And I attached a photo too.

I searched some issues and Tzahi said them to configure with Youtube DLC, not DL. But since I'm not familiar with docker environment, I don't know how to change to DLC.

Can you give me how to do it or is there something more great way to fix this problem?
Thanks.

![1](https://user-images.githubusercontent.com/42744904/133551943-44ac8eb8-e7c1-45d4-b8f0-3e20862978a6.png)
![2](https://user-images.githubusercontent.com/42744904/133551950-f174e666-be07-4612-bfd9-0de4f173f919.png)
![3](https://user-images.githubusercontent.com/42744904/133551953-98af5786-c748-4075-aa75-cdcb008321df.png)
![4](https://user-images.githubusercontent.com/42744904/133551955-225c498c-ff5d-44e0-9b33-09270a9a235b.png)

**Comment by GlassedSilver** [comment]
Personally I prefer to stay on the OG myself (personal preference and a reluctance to be skippy with forks in general with software), but if you're willing to switch forks that's no problem. :)

Just follow along:

**Settings > Advanced > "Select a downloader"**

![image](https://user-images.githubusercontent.com/1912133/133552323-37d334c4-e22f-4da7-8200-fb86a5a94b27.png)

Nothing Docker specific, you can all do it from within the app itself. :)

Hope it helps. Let me know if you need anything else :)

**Comment by u0a** [comment]
> Personally I prefer to stay on the OG myself (personal preference and a reluctance to be skippy with forks in general with software), but if you're willing to switch forks that's no problem. :)
> 
> Just follow along:
> 
> **Settings > Advanced > "Select a downloader"**
> 
> ![image](https://user-images.githubusercontent.com/1912133/133552323-37d334c4-e22f-4da7-8200-fb86a5a94b27.png)
> 
> Nothing Docker specific, you can all do it from within the app itself. :)
> 
> Hope it helps. Let me know if you need anything else :)

Oh, thanks. I thought it was very hard to change.
But still same error even I changed downloader to dlc..
Is there any way to fix this error?

Log : 
2021-09-16T05:02:45.990Z ERROR: Error during parsing: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json http://www.youtube.com/watch?v=qo7ae99w1IQ
2021-09-16T05:02:45.995Z ERROR: failed to parse for urls starting with https://www.youtube.com/watch?v=qo7ae99w1IQ
2021-09-16T05:02:49.976Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=qo7ae99w1IQ with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=qo7ae99w1IQ
2021-09-16T05:02:49.978Z ERROR: ERROR: Unable to download webpage: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again'),))

**Comment by GlassedSilver** [comment]
Looks like you're still using youtube-dl. Did you press save after changing the setting? (sorry I forgot to point that out, My bad!)

![image](https://user-images.githubusercontent.com/1912133/133553349-8806138c-2fa7-40c8-a6db-8b7072d8698d.png)

**Comment by u0a** [comment]
> Looks like you're still using youtube-dl. Did you press save after changing the setting? (sorry I forgot to point that out, My bad!)
> 
> ![image](https://user-images.githubusercontent.com/1912133/133553349-8806138c-2fa7-40c8-a6db-8b7072d8698d.png)

Yeah I thought that is strange but I already pressed Save button.
I restarted the container but it didn't start.
Maybe something went wrong.. I'll reinstall the container.

**Comment by GlassedSilver** [comment]
Keep us updated, if it fails again maybe @Tzahi12345 can figure it out better than I could. Just in case you might want to trail the log as it loads up and share a snippet of that. Can't really help with Synology specifically here, but the log will be in the appdata folder (the path defined as `/app/appdata` so `docker/youtubedl/app` on your Synology machine)

**Comment by u0a** [comment]
> Keep us updated, if it fails again maybe @Tzahi12345 can figure it out better than I could. Just in case you might want to trail the log as it loads up and share a snippet of that. Can't really help with Synology specifically here, but the log will be in the appdata folder (the path defined as `/app/appdata` so `docker/youtubedl/app` on your Synology machine)

I reinstalled many times and also downgraded but the problem occured again.
I think it is youtube dl or dlc's problem but well I can't handle this problem.
So, well, I'll wait for @Tzahi12345 and this is my log : 

2021-09-16T06:13:03.942Z INFO: Cannot find config file. Creating one with default values...
2021-09-16T06:13:03.995Z INFO: Beginning migration: 4.1->4.2+
2021-09-16T06:13:04.017Z INFO: 4.1->4.2+ migration complete!
2021-09-16T06:13:09.137Z ERROR: youtube-dl failed to update. Restart the server to try again.
2021-09-16T06:13:09.138Z ERROR: getaddrinfo EAI_AGAIN yt-dl.org
2021-09-16T06:13:09.140Z INFO: youtube-dl successfully updated!
2021-09-16T06:13:09.152Z INFO: YoutubeDL-Material v4.2 started on PORT 17442
 [ I changed downloader to youtube-dlc and tried to download video ]
2021-09-16T06:14:12.865Z ERROR: Error during parsing: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json http://www.youtube.com/watch?v=qo7ae99w1IQ
2021-09-16T06:14:12.866Z ERROR: failed to parse for urls starting with https://www.youtube.com/watch?v=qo7ae99w1IQ
2021-09-16T06:14:24.817Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=qo7ae99w1IQ with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=qo7ae99w1IQ
2021-09-16T06:14:24.819Z ERROR: ERROR: Unable to download webpage: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again'),))
 [ I restarted this container ]
2021-09-16T06:15:03.285Z ERROR: Failed to check youtube-dlc version for an update.
2021-09-16T06:15:03.291Z ERROR: request to https://api.github.com/repos/blackjack4494/yt-dlc/tags failed, reason: getaddrinfo EAI_AGAIN api.github.com
2021-09-16T06:15:17.280Z ERROR: Failed to check youtube-dlc version for an update.
2021-09-16T06:15:17.287Z ERROR: request to https://api.github.com/repos/blackjack4494/yt-dlc/tags failed, reason: getaddrinfo EAI_AGAIN api.github.com
 [ Endless repeat ]

**Comment by Tzahi12345** [comment]
You can also try yt-dlp if you're on the latest nightly.

Someone else did see the exact same error, and it looks like [their solution](https://github.com/Tzahi12345/YoutubeDL-Material/issues/95#issuecomment-768282014) worked. Check it out and let me know how it goes!

**Comment by GlassedSilver** [comment]
Depending on what kinds of arguments you use you might want to find out if the fork you switch to uses them differently or dropped support for them.

For example I know that youtube-dlp (I think) uses a light version of the info json. There is a flag to write the classic format to disk though. Just as a little explanation why specifically with youtube-dl I'm extremely conservative.

**Comment by Tzahi12345** [comment]
I actually specifically asked the dev to add an argument to keep more info in the JSON, otherwise it would be impossible for us to use. But yeah definitely something to keep in mind!

**Comment by u0a** [comment]
Thank you for your effort, and I solved it by unlocking all firewall settings for private ip.
However, I installed the nightly version to use dlp, but it was not executed due to the following error. Now, there is no reason for me to install the nightly version since I have solved my problem, but I'm simply informing you for bug report.
 
2021-09-17 00:18:48 stdout internal/modules/cjs/loader.js:818
2021-09-17 00:18:46 stdout error: Script restart attempt #1
2021-09-17 00:18:46 stdout error: Forever detected script exited with code: 1
2021-09-17 00:18:46 stdout }
2021-09-17 00:18:46 stdout  requireStack: [ '/app/db.js', '/app/app.js' ]
2021-09-17 00:18:46 stdout  code: 'MODULE_NOT_FOUND',
2021-09-17 00:18:46 stdout    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
2021-09-17 00:18:46 stdout    at Module.load (internal/modules/cjs/loader.js:863:32)
2021-09-17 00:18:46 stdout    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-09-17 00:18:46 stdout    at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-09-17 00:18:46 stdout    at Object.<anonymous> (/app/app.js:13:16)
2021-09-17 00:18:46 stdout    at require (internal/modules/cjs/helpers.js:74:18)
2021-09-17 00:18:46 stdout    at Module.require (internal/modules/cjs/loader.js:887:19)
2021-09-17 00:18:46 stdout    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-09-17 00:18:46 stdout    at Module.load (internal/modules/cjs/loader.js:863:32)
2021-09-17 00:18:46 stdout    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-09-17 00:18:46 stdout    at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-09-17 00:18:46 stdout    at Object.<anonymous> (/app/db.js:12:29)
2021-09-17 00:18:46 stdout    at require (internal/modules/cjs/helpers.js:74:18)
2021-09-17 00:18:46 stdout    at Module.require (internal/modules/cjs/loader.js:887:19)
2021-09-17 00:18:46 stdout    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-09-17 00:18:46 stdout    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-09-17 00:18:46 stdout - /app/app.js
2021-09-17 00:18:46 stdout - /app/db.js
2021-09-17 00:18:46 stdout Require stack:
2021-09-17 00:18:46 stdout Error: Cannot find module 'rxjs'
2021-09-17 00:18:46 stdout
2021-09-17 00:18:46 stdout  ^
2021-09-17 00:18:46 stdout  throw err;
2021-09-17 00:18:46 stdout internal/modules/cjs/loader.js:818
2021-09-17 00:18:42 stdout [33mwarn[39m:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
2021-09-17 00:18:42 stdout [33mwarn[39m:    --minUptime not set. Defaulting to: 1000ms
[ And repeat ]

**Comment by u0a** [comment]
And I'm now curious is there any way to encode video file to h264 in ytdl-material?
Since I'm using mac and ios, I cannot play vp9 and opus(not sure) codec not using third-party player. So I'd like to change it to h264 and aac, or anything else.
I found there is --encoding option, but I couldn't find how to use it.
If you don't mind, can you tell me how to use it?

**Comment by GlassedSilver** [comment]
Running into the same error:

```
error: Forever detected script exited with code: 1
error: Script restart attempt #128
internal/modules/cjs/loader.js:818
throw err;
^

Error: Cannot find module 'rxjs'
Require stack:
- /app/db.js
- /app/app.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/db.js:12:29)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/app.js:13:16)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/db.js', '/app/app.js' ]
}
error: Forever detected script exited with code: 1
error: Script restart attempt #129
internal/modules/cjs/loader.js:818
throw err;
^

Error: Cannot find module 'rxjs'
Require stack:
- /app/db.js
- /app/app.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/db.js:12:29)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/app.js:13:16)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/db.js', '/app/app.js' ]
}
error: Forever detected script exited with code: 1
error: Script restart attempt #130
internal/modules/cjs/loader.js:818
throw err;
^
```

etc etc...

This is on the latest nightly after the first try to start it up.

This is with the downloader fork set to regular youtube-dl. So it's not because of that I think.

**Comment by GlassedSilver** [comment]
> 
> And I'm now curious is there any way to encode video file to h264 in ytdl-material? Since I'm using mac and ios, I cannot play vp9 and opus(not sure) codec not using third-party player. So I'd like to change it to h264 and aac, or anything else. I found there is --encoding option, but I couldn't find how to use it. If you don't mind, can you tell me how to use it?



> 
> And I'm now curious is there any way to encode video file to h264 in ytdl-material? Since I'm using mac and ios, I cannot play vp9 and opus(not sure) codec not using third-party player. So I'd like to change it to h264 and aac, or anything else. I found there is --encoding option, but I couldn't find how to use it. If you don't mind, can you tell me how to use it?

You can look up the documentation for youtube-dl here:

https://github.com/ytdl-org/youtube-dl/blob/master/README.md#workarounds

I linked you right to the relevant part. Unfortunately the documentation doesn't get much more specific than that. Maybe if you just pass HEVC (that should be hardware-decoded on basically anything modern these days, in Apple land as well) it SHOULD work I guess?

Not sure if it would also be advisable to force a container along with that, shouldn't be necessary though. Not sure anymore, haven't checked that in a while.

Cheers and hope this is somewhat helpful.

**Comment by Tzahi12345** [comment]
>However, I installed the nightly version to use dlp, but it was not executed due to the following error. Now, there is no reason for me to install the nightly version since I have solved my problem, but I'm simply informing you for bug report.

Oops missed an import! [Should be fixed now](https://github.com/Tzahi12345/YoutubeDL-Material/commit/f689609941258fa93219937080c846c7909ef3a0).

**Comment by u0a** [comment]
If anyone who uses synology or anything else suffers from the same problem as me, it would be nice to guide them to turn off the firewall. Really thanks for your help and I'll close this issue.

**Comment by GlassedSilver** [comment]
> 
> 
> > However, I installed the nightly version to use dlp, but it was not executed due to the following error. Now, there is no reason for me to install the nightly version since I have solved my problem, but I'm simply informing you for bug report.
> 
> Oops missed an import! [Should be fixed now](https://github.com/Tzahi12345/YoutubeDL-Material/commit/f689609941258fa93219937080c846c7909ef3a0).

Nice! Just gonna wait for DockerHub to catch up to the latest commit then and then it's party time!

Can't wait to see the new download backend in action! :D

**Comment by GlassedSilver** [comment]
> 
> 
> If anyone who uses synology or anything else suffers from the same problem as me, it would be nice to guide them to turn off the firewall. Really thanks for your help and I'll close this issue.

We'll bring it to anyone's attention if raised directly again to us, additionally I created a notice page for Synology in the Wiki. :)

https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Synology

**Comment by u0a** [comment]
> We'll bring it to anyone's attention if raised directly again to us, additionally I created a notice page for Synology in the Wiki. :)
> 
> https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Synology

Thanks :)

**Comment by jwillmer** [comment]
works again

**Comment by GlassedSilver** [comment]
> works again

Can confirm, seems pretty good so far, let's see how this one handles busy sub peaks :)
