### ISSUE TITLE
[BUG]  Error: Cannot find module 'rxjs'

### ISSUE THREAD

**Issue by NOForker** [Tzahi12345/YoutubeDL-Material#451]
**Describe the bug**
The latest Docker nightly image is reporting rxjs module is missing.

**To Reproduce**
Start Docker image

**Environment**
- Docker tag: nightly

**Additional context**
Logs:

Error: Cannot find module 'rxjs'

Require stack:

- /app/db.js

- /app/app.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/app/db.js:12:29)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/app/app.js:13:16)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [ '/app/db.js', '/app/app.js' ]

}

error: Forever detected script exited with code: 1

**Comment by NOForker** [comment]
Read in a different thread that this is resolved. So, I removed my Docker container and reinstalled, but this issue is still happening.

**Comment by GlassedSilver** [comment]
You removed the container, but did you also remove the container's image?

Sounds like Docker isn't pulling the latest image from DockerHub, because a recent (but in our case not recent enough) image is still on disk.

**Comment by NOForker** [comment]
@GlassedSilver Yep! That was It! All good now.
