### ISSUE TITLE
youtube-dl module not found

### ISSUE THREAD

**Issue by captainwasabi** [Tzahi12345/YoutubeDL-Material#5]
# nodejs app.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'youtube-dl'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/backend/app.js:4:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by captainwasabi** [comment]
Install section in the docs should include that you have to run "npm install" from the backend directory

**Comment by Tzahi12345** [comment]
> Install section in the docs should include that you have to run "npm install" from the backend directory

You're completely right, I'll update the README to include this.

**Comment by Tzahi12345** [comment]
Done! Thanks for pointing this out :)
