### ISSUE TITLE
[BUG] LOG entries: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 && <= 17825792.

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#565]
**Describe the bug**
Some downloads cause this to appear in the log:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825795
at validateOffset (node:buffer:115:3)
at Buffer.write (node:buffer:1066:5)
at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:342:14)
at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:729:17)
at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)
at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:127:22)
at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:119:33)
at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:105:25) {
code: 'ERR_OUT_OF_RANGE'
}
```

Not sure what this will cause for our instance's mongoDB data integrity?

**To Reproduce**

I get this on some subscription downloads (and I think one-offs as well).

I'm sussing this may have something to do with the info.json being too large to ingress into mongodb when you have enabled to download comments, since they all get written into the info.json.

**Expected behavior**

for the log to not receive this STERR and if my assumption above about the reason for this appearing is correct:

Maybe YTDL-M should truncate the comment part out of the query to mongoDB and rely on the info.json to load the comments when we implement displaying them. (#289) Writing to the DB that we DO have the comments downloaded would suffice.

**Screenshots**
n/a

**Environment**

- Installed version: v4.2
- Installation type: docker
Docker tag: nightly
Commit hash: d5c1361
Build date: 2022-04-24 

**Additional context**
n/a

**Comment by Tzahi12345** [comment]
We strip out most of the metadata to keep the records small. See [db.js:generateFileObject()](https://github.com/Tzahi12345/YoutubeDL-Material/blob/5e239321462dc0997f9880c017c36c2a6e350da0/backend/db.js#L208) for all the data we keep. This is probably reproducible though, do you have a link for the video that caused the error?

**Comment by GlassedSilver** [comment]
Sadly I cannot find that error anymore in my logs. Maybe it got fixed at some point. If it happens again I'll reopen this issue. :)

**Comment by zerojay** [comment]
Getting this same issue right now on latest docker with the following video URL: https://www.youtube.com/watch?v=1BVmJlTteQo

**Comment by zerojay** [comment]
Actually, it appears to be a problem with *every* video.

**Comment by martadinata666** [comment]
Currently please use `nightly` tag rather `latest` tag.

**Comment by zerojay** [comment]
I already am using the nightly tag.

**Comment by martadinata666** [comment]
I just can report that i can't replicate. And when it told that `every` video, i think some messed on installation? I just can suggest start from scratch.

**Comment by zerojay** [comment]
This is not a new installation, though I did attempt to switch to mongodb right when this started happening. But the container just no longer appears to start up at all using local db.

**Comment by Tzahi12345** [comment]
> This is not a new installation, though I did attempt to switch to mongodb right when this started happening. But the container just no longer appears to start up at all using local db.

Can you give a few more details/logs? It should be relatively easy to switch back

The error appears to be MongoDB related, not surprised it only happens then
