### ISSUE TITLE
[BUG] LOG entries: TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#567]
**Describe the bug**

Logging of following error: (sample entry, not specific to checked channel)
```
2022-04-26T07:00:30.639Z VERBOSE: Subscription: finished check for Chino
TypeError: Cannot read properties of undefined (reading 'forEach')
at setFreshUploads (/app/subscriptions.js:478:16)
at /app/subscriptions.js:299:27
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**

This occurs when using subscriptions. Not sure if this happens for all subs occasionally or just for some.

It doesn't seem to stop subs appearing at all, but it causing a lot of noise in the log and I'm not sure how severe this is.

Been an issue for a good long while now.

**Expected behavior**

The log to stay tidy and neat :P

**Screenshots**
n/a

**Environment**
- Installed version: v4.2
- Installation type: docker
Docker tag: nightly
Commit hash: 4dd3b97
Build date: 2022-04-26 

**Additional context**
n/a

**Comment by Tzahi12345** [comment]
Should be fixed! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/5e3eb68b03f780dfc3b605cc1a5bfb6c9ab1e630).
