### ISSUE TITLE
Error during posintall script during npm install

### ISSUE THREAD

**Issue by Wibbbs** [Tzahi12345/YoutubeDL-Material#6]
Ran npm install on the main dir (front end) and received the following error durinf the post install script.
```

> youtube-dl-material@0.0.0 postinstall C:\Users\username\YouTubeDL\YoutubeDL-Material
> ng build --prod && mkdir dist/backend && mkdir dist/backend/config && mkdir dist/backend/audio && mkdir dist/backend/video && cp src/assets/default.json dist/backend/config/default.json && cp backend/app.js dist/backend/app.js

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.c5fa8325f89fc516600b.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.c5fa8325f89fc516600b.js (runtime) 1.45 kB [entry] [rendered]
chunk {2} polyfills-es2015.b0638ec1e72267738494.js (polyfills) 82 kB [initial] [rendered]
chunk {3} polyfills-es5.12553af63efad0b3e192.js (polyfills-es5) 172 kB [initial] [rendered]
chunk {1} main-es2015.ab362dbf073a0f09d159.js (main) 1.11 MB [initial] [rendered]
chunk {1} main-es5.ab362dbf073a0f09d159.js (main) 1.28 MB [initial] [rendered]
chunk {4} styles.3889f9a03e77147fd89c.css (styles) 177 kB [initial] [rendered]
Date: 2020-02-24T14:40:54.559Z - Hash: ec1d0da4cb79918ca13c - Time: 112975ms
The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl-material@0.0.0 postinstall: `ng build --prod && mkdir dist/backend && mkdir dist/backend/config && mkdir dist/backend/audio && mkdir dist/backend/video && cp src/assets/default.json dist/backend/config/default.json && cp backend/app.js dist/backend/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl-material@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-02-24T14_40_54_823Z-debug.log
```

**Comment by Wibbbs** [comment]
Closer look at the debug log shows the following.

```
39611 silly lifecycle   'ng build --prod && mkdir dist/backend && mkdir dist/backend/config && mkdir dist/backend/audio && mkdir dist/backend/video && cp src/assets/default.json dist/backend/config/default.json && cp backend/app.js dist/backend/app.js' ]
39612 silly lifecycle youtube-dl-material@0.0.0~postinstall: Returned: code: 1  signal: null
39613 info lifecycle youtube-dl-material@0.0.0~postinstall: Failed to exec postinstall script
39614 verbose stack Error: youtube-dl-material@0.0.0 postinstall: `ng build --prod && mkdir dist/backend && mkdir dist/backend/config && mkdir dist/backend/audio && mkdir dist/backend/video && cp src/assets/default.json dist/backend/config/default.json && cp backend/app.js dist/backend/app.js`
39614 verbose stack Exit status 1
39614 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
39614 verbose stack     at EventEmitter.emit (events.js:182:13)
39614 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
39614 verbose stack     at ChildProcess.emit (events.js:182:13)
39614 verbose stack     at maybeClose (internal/child_process.js:962:16)
39614 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
39615 verbose pkgid youtube-dl-material@0.0.0
39616 verbose cwd C:\Users\username\YouTubeDL\YoutubeDL-Material
39617 verbose Windows_NT 10.0.17763
39618 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andrew.wiebe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
39619 verbose node v10.15.0
39620 verbose npm  v6.13.4
39621 error code ELIFECYCLE
39622 error errno 1
39623 error youtube-dl-material@0.0.0 postinstall: `ng build --prod && mkdir dist/backend && mkdir dist/backend/config && mkdir dist/backend/audio && mkdir dist/backend/video && cp src/assets/default.json dist/backend/config/default.json && cp backend/app.js dist/backend/app.js`
39623 error Exit status 1
39624 error Failed at the youtube-dl-material@0.0.0 postinstall script.
39624 error This is probably not a problem with npm. There is likely additional logging output above.
39625 verbose exit [ 1, true ]
```

**Comment by Wibbbs** [comment]
I think this might be because I am building on windows.

**Comment by Tzahi12345** [comment]
I actually think this is my fault from some last minute updates. I updated the package.json on the frontend on the master branch, let me know if that fixes your issues.

**Comment by Tzahi12345** [comment]
@Wibbbs By the way, you only need to build the frontend if you're looking to develop, otherwise you can just use the releases [here.](https://github.com/Tzahi12345/YoutubeDL-Material/releases)

**Comment by Tzahi12345** [comment]
Closing for inactivity, problem should be resolved - if anyone has any more issues with manually building, feel free to open up another issue.
