### ISSUE TITLE
[BUG] Unable to Connect on Nightly Docker Build

### ISSUE THREAD

**Issue by ierc** [Tzahi12345/YoutubeDL-Material#661]
**Describe the bug**
The Nightly docker build stopped working all of a sudden. I'm getting "unable to connect" errors, but when I roll back to 4.2 it loads fine (but the downloads are extremely slow)

**To Reproduce**
Try access container while on nightly release

**Expected behavior**
interface should load

**Screenshots**
https://imgur.com/OCi678s

**Environment**
- Nightly build
- :Nightly

**Comment by ofifoto** [comment]
I'm seeing the same thing.. I think:

```
$ docker-compose up                               
Pulling ytdl_material (tzahi12345/youtubedl-material:nightly)...
nightly: Pulling from tzahi12345/youtubedl-material
d7bfe07ed847: Already exists
3a84e9933e54: Pull complete
4bdf6cad814b: Pull complete
ff57c001ee6f: Pull complete
26c85ea42e4d: Pull complete
2a8f42ac3d05: Pull complete
a8ea9995385f: Pull complete
f0149707bc12: Pull complete
c7e1edd871ed: Pull complete
Digest: sha256:90d569de5a95f7dc88d87323f295e73ff19a5b44bb02a4d5cef76104d27d362e
Status: Downloaded newer image for tzahi12345/youtubedl-material:nightly
Creating mongo-db ... done
Creating youtubedl-material_ytdl_material_1 ... done
Attaching to mongo-db, youtubedl-material_ytdl_material_1
mongo-db         | WARNING: no logs are available with the 'none' log driver
ytdl_material_1  | 2022-06-21T23:01:17: PM2 log: Launching in no daemon mode
ytdl_material_1  | 2022-06-21T23:01:17: PM2 log: [Watch] Start watching YoutubeDL-Material
ytdl_material_1  | 2022-06-21T23:01:17: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
ytdl_material_1  | 2022-06-21T23:01:17: PM2 log: App [YoutubeDL-Material:0] online
ytdl_material_1  | 2022-06-21T23:01:18.830Z INFO: Config items set using ENV variables.
ytdl_material_1  | TypeError: Cannot read properties of null (reading 'includes')
ytdl_material_1  |     at Object.exports.verifyBinaryExistsLinux (/app/youtube-dl.js:93:62)
ytdl_material_1  |     at startYoutubeDL (/app/app.js:671:19)
ytdl_material_1  |     at loadConfig (/app/app.js:514:11)
ytdl_material_1  |     at async setAndLoadConfig (/app/app.js:483:5)
ytdl_material_1  | 2022-06-21T23:01:22.866Z VERBOSE: Disabling checking downloads as none are available.
```

**Comment by Tzahi12345** [comment]
Whoops, my bad! Hotfixed with https://github.com/Tzahi12345/YoutubeDL-Material/commit/6fa4296edfbc7d3201a9722558e171d29f486537. Thanks for the report!

**Comment by ofifoto** [comment]
All good; thank you so much!

**Comment by ierc** [comment]
Thanks for the quick fix!
