### ISSUE TITLE
[BUG] forEach error on undefined when trying to get file size for file with no formats

### ISSUE THREAD

**Issue by FoxxMD** [Tzahi12345/YoutubeDL-Material#674]
**Describe the bug**

Additional options:

* `Allow quality select` disabled

After hitting Download the video goes into the queue with Stage `Getting Info` and then hangs. This is what appears in the log:

```
2022-06-28T14:55:04.357Z VERBOSE: Collecting info for download 90a14fdc-386f-46d9-89ba-897496d3eaa0
2022-06-28T14:55:04.364Z VERBOSE: yt-dlp args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,--write-thumbnail,--no-clean-infojson
TypeError: Cannot read properties of undefined (reading 'forEach')
at /app/utils.js:175:31
at Array.forEach (<anonymous>)
at /app/utils.js:174:17
at Array.forEach (<anonymous>)
at Object.getExpectedFileSize (/app/utils.js:171:16)
at collectInfo (/app/downloader.js:213:38)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behavior**

Expected video to download. yt-dlp is able to download the same video when used in [metube](https://github.com/alexta69/metube)

**Environment**
- Downloader `yt-dlp`

```
Installed version: v4.3 -   You are up to date.
Installation type: docker
Docker tag: latest
Commit hash: e726e99
Build date: 2022-06-27
```

**Additional context**

This is on a certain site that is not Youtube but is still supported [by yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md)

**Comment by FoxxMD** [comment]
This is not the same issue, look at the trace

**Comment by GlassedSilver** [comment]
My bad, sorry!
