### ISSUE TITLE
[BUG] When the config file is not found, the error is caught and then null is returned—but an object is expected.

### ISSUE THREAD

**Issue by RosemaryOrchard** [Tzahi12345/YoutubeDL-Material#694]
**Describe the bug**

**To Reproduce**
1. Make sure your config file is missing
2. `npm start`
3. Wait for it...
4. The following error message appears:
```sh
ERROR: Failed to get config file
TypeError: Cannot use 'in' operator to search for 'YoutubeDLMaterial' in null
    at Function.Object.byString (/home/rose/youtubedl-material-temp/config.js:37:15)
    at getConfigItem (/home/rose/youtubedl-material-temp/config.js:97:24)
    at ensureConfigItemsExist (/home/rose/youtubedl-material-temp/config.js:19:9)
    at Object.initialize (/home/rose/youtubedl-material-temp/config.js:12:5)
    at Object.<anonymous> (/home/rose/youtubedl-material-temp/app.js:59:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Object.<anonymous> (/home/rose/youtubedl-material-temp/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Expected behavior**
If the config file cannot be found, it should not then continue to be processed as an object—or if it should then an object ought to be returned rather than null.

**Environment**
- YoutubeDL-Material version 4.3

**Additional context**
The error is caused by the [`Object.byString`](https://github.com/Tzahi12345/YoutubeDL-Material/blob/24475386f99683ee5c3b56bcd9e853068af0f9f9/backend/config.js#L37)
However the real culprit is [`getConfigFile()`](https://github.com/Tzahi12345/YoutubeDL-Material/blob/24475386f99683ee5c3b56bcd9e853068af0f9f9/backend/config.js#L70-L79)
```js
function getConfigFile() {
    try {
        let raw_data = fs.readFileSync(configPath);
        let parsed_data = JSON.parse(raw_data);
        return parsed_data;
    } catch(e) {
        logger.error('Failed to get config file');
        return null;
    }
}
```

I've not followed the logic through yet to find out if the `null` should have been caught somewhere else and already replaced with the default config—but either that should happen or at least an empty object should be returned.

**Comment by RosemaryOrchard** [comment]
This was happening as there was a rogue comma in my JSON file which meant the file itself was present—but couldn't be parsed.

**Comment by Tzahi12345** [comment]
> This was happening as there was a rogue comma in my JSON file which meant the file itself was present—but couldn't be parsed.

Oh ok! So it sounds like it was resolved? We can also convert this issue to deal with the error-handling part which would've made the issue more clear.
