### ISSUE TITLE
[BUG] Malformed JSON in local_db.json

### ISSUE THREAD

**Issue by jwillmer** [Tzahi12345/YoutubeDL-Material#747]
**Describe the bug**
I try to start the docker image but get constant restarts with the following log output. The `local_db.json` is around 120MB in size - if that makes any difference.

**Expected behavior**
The app will start up.

**Screenshots**
```
2022-09-06T22:12:32: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2022-09-06T22:12:32: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2022-09-06T22:12:32: PM2 log: App [YoutubeDL-Material:0] online
SyntaxError: Malformed JSON in file: ./appdata/local_db.json
Unexpected end of JSON input
    at FileSync.parse [as deserialize] (<anonymous>)
    at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:37:30)
    at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
    at Object.<anonymous> (/app/db.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Environment**
- Docker tag: nightly

**Comment by Tzahi12345** [comment]
Sorry for the late response.. if you'd be comfortable can you email me the JSON file so I can look at it? You can send it here: [tzahi2g@gmail.com](mailto:tzahi2g@gmail.com)

It's best to use MongoDB if you can, not sure what caused this but it wouldn't be possible.

**Comment by jwillmer** [comment]
I don't have it anymore. Closing it,
