### ISSUE TITLE
[BUG] Unable to Transfer DB to Mongo

### ISSUE THREAD

**Issue by thotmail** [Tzahi12345/YoutubeDL-Material#861]
**Describe the bug**
Upon attempting to transfer from local to Mongo, the web logs say DEBUG: Database cleared! Beginning transfer.
But still indicates DB is Local.

**To Reproduce**
1. Go to Settings -> Database
2. Click on Transfer BD to MongoDB
3. Wait, Refresh Database is still Local

**Expected behavior**
Database goes to MongoDB

**Screenshots**
![image](https://user-images.githubusercontent.com/65213509/232253285-2d6cea36-aa01-46cd-b497-b256e92cb970.png)

**Environment**
- YoutubeDL-Material version: 4.3
- Docker tag: nightly-2023-04-04

Installed version: v4.3.1 -   [Update available - v4.3](https://github.com/Tzahi12345/YoutubeDL-Material/releases/latest). You can update from the settings menu.
Installation type: docker
Docker tag: nightly
Commit hash: 12e69af
Build date: 2023-04-04

**Additional context**
Add any other context about the problem here. For example, a YouTube link.

**Comment by thotmail** [comment]
Looked into Docker logs:
```
2023-04-15T20:55:51.028Z DEBUG: Database cleared! Beginning transfer.
Error: key options.auto_confirm must not contain '.'
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:921:19)
    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:729:17)
    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:947:17)
    at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:127:22)
    at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:119:33)
    at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:105:25)
    at MessageStream.writeCommand (/app/node_modules/mongodb/lib/cmap/message_stream.js:61:69)
    at Connection.write (/app/node_modules/mongodb/lib/cmap/connection.js:400:26)
    at _command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:149:10)
    at command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
    at writeCommand (/app/node_modules/mongodb/lib/core/wireprotocol/write_command.js:56:3)
    at Object.insert (/app/node_modules/mongodb/lib/core/wireprotocol/index.js:6:5)
    at Connection.insert (/app/node_modules/mongodb/lib/cmap/connection.js:218:8)
    at /app/node_modules/mongodb/lib/core/sdam/server.js:492:13
    at Object.callback (/app/node_modules/mongodb/lib/cmap/connection_pool.js:347:7)
    at processWaitQueue (/app/node_modules/mongodb/lib/cmap/connection_pool.js:470:23)
    at /app/node_modules/mongodb/lib/cmap/connection_pool.js:238:28
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by Tzahi12345** [comment]
Can you share the tasks portion of your `local_db.json`? It's in `appdata` and the excerpt I'm looking for should look something like this:

<details>
    <summary>Local DB Tasks Excerpt</summary>

```json

"tasks": [
    {
      "key": "backup_local_db",
      "title": "Backup DB",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "missing_files_check",
      "title": "Missing files check",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "missing_db_records",
      "title": "Import missing DB records",
      "last_ran": 1673934493.076,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "duplicate_files_check",
      "title": "Find duplicate files in DB",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "youtubedl_update_check",
      "title": "Update youtube-dl",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "delete_old_files",
      "title": "Delete old files",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "import_legacy_archives",
      "title": "Import legacy archives",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    }
  ],

```
</details>

**Comment by thotmail** [comment]
<details><summary>Looks a Bit different</summary>
<p>

```
"tasks": [
    {
      "_id": "62d4da18171354003a5f711c",
      "key": "backup_local_db",
      "title": "Backup DB",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {},
      "options.auto_confirm": false
    },
    {
      "_id": "62d4da18171354003a5f711d",
      "key": "missing_files_check",
      "title": "Missing files check",
      "last_ran": 1681524000.056,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": {
        "uids": []
      },
      "error": null,
      "schedule": {
        "type": "recurring",
        "data": {
          "hour": 2,
          "minute": 0
        }
      },
      "options": {},
      "next_invocation": 1681610400000,
      "options.auto_confirm": false
    },
    {
      "_id": "62d4da18171354003a5f711e",
      "key": "missing_db_records",
      "title": "Import missing DB records",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {},
      "options.auto_confirm": false
    },
    {
      "_id": "62d4da18171354003a5f711f",
      "key": "duplicate_files_check",
      "title": "Find duplicate files in DB",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {},
      "options.auto_confirm": false
    },
    {
      "_id": "62d4da18171354003a5f7120",
      "key": "youtubedl_update_check",
      "title": "Update youtube-dl",
      "last_ran": 1681592105.893,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": {
        "type": "recurring",
        "data": {
          "hour": 1,
          "minute": 1
        }
      },
      "options": {},
      "next_invocation": 1681606860000,
      "options.auto_confirm": false
    },
    {
      "key": "delete_old_files",
      "title": "Delete old files",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    },
    {
      "key": "import_legacy_archives",
      "title": "Import legacy archives",
      "last_ran": null,
      "last_confirmed": null,
      "running": false,
      "confirming": false,
      "data": null,
      "error": null,
      "schedule": null,
      "options": {
        "auto_confirm": false,
        "blacklist_files": false,
        "blacklist_subscription_files": false,
        "threshold_days": ""
      }
    }
  ]
```

</p>
</details>

**Comment by Tzahi12345** [comment]
I think I fixed this with the latest commit: https://github.com/Tzahi12345/YoutubeDL-Material/commit/ca5381fe0f7766acb9df9e3336e964000a792490

Can you confirm? Just pull the latest nightly, and on startup the DB situation should be resolved.

**Comment by thotmail** [comment]
Confirmed, resolving
