### ISSUE TITLE
[BUG] Upgrade downloader to v4.3 failed

### ISSUE THREAD

**Issue by HxBreak** [Tzahi12345/YoutubeDL-Material#874]
**Describe the bug**
Upgrade downloader to v4.3 failed

I used latest docker-compose.yml in release page
I can't even to download any youtube video, Can i to active some debug option to know where trigger this error?
Or some action can manually solve this issue.

**To Reproduce**
1. Go to Setting
2. Click on Downloader
3. Scroll down to upgrade to ytb-dl v4.3

**Expected behavior**

**Screenshots**
```
Creating mongo-db ... done
Creating youtube_ytdl_material_1 ... done
Attaching to youtube_ytdl_material_1
ytdl_material_1  | 2023-04-22T16:49:07.814Z INFO: Cannot find config file. Creating one with default values...
ytdl_material_1  | 2023-04-22T16:49:07.852Z INFO: Config items set using ENV variables.
ytdl_material_1  | 2023-04-22T16:49:07.955Z INFO: Beginning migration: 4.1->4.2+
ytdl_material_1  | 2023-04-22T16:49:08.075Z INFO: 4.1->4.2+ migration complete!
ytdl_material_1  | 2023-04-22T16:49:12.560Z INFO: youtube-dl successfully updated!
ytdl_material_1  | 2023-04-22T16:49:12.563Z INFO: YoutubeDL-Material v4.2 started on PORT 17442
ytdl_material_1  | 2023-04-22T16:49:32.810Z ERROR: ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ytdl_material_1  | 2023-04-22T16:49:32.810Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.
ytdl_material_1  | 2023-04-22T16:51:45.047Z ERROR: Error during parsing: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json http://www.youtube.com/watch?v=VGL4bfXXhXg
ytdl_material_1  | 2023-04-22T16:51:45.047Z ERROR: failed to parse for urls starting with https://www.youtube.com/watch?v=VGL4bfXXhXg
ytdl_material_1  | 2023-04-22T16:51:45.984Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=VGL4bfXXhXg with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=VGL4bfXXhXg
ytdl_material_1  | 2023-04-22T16:51:45.984Z ERROR: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ytdl_material_1  | 2023-04-22T16:52:18.179Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=VGL4bfXXhXg with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=VGL4bfXXhXg
ytdl_material_1  | 2023-04-22T16:52:18.179Z ERROR: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ytdl_material_1  | 2023-04-22T16:52:41.949Z INFO: Backing up your non-video/audio files to appdata/backups/backup-1682182361949.zip. This may take up to a few seconds/minutes.
ytdl_material_1  | 2023-04-22T16:52:48.521Z INFO: Downloading new files...
ytdl_material_1  | 2023-04-22T16:52:49.107Z INFO: Installing update v4.3...
ytdl_material_1  | Unhandled rejection Error: invalid signature: 0x20746f4e
ytdl_material_1  |     at /app/node_modules/unzipper/lib/parse.js:66:26
ytdl_material_1  |     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
ytdl_material_1  |     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31)
ytdl_material_1  |     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18)
ytdl_material_1  |     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
ytdl_material_1  |     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18)
ytdl_material_1  |     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
ytdl_material_1  |     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
ytdl_material_1  |     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
ytdl_material_1  |     at processImmediate (internal/timers.js:461:21)


```

**Environment**
- YoutubeDL-Material version
- Docker tag: 23.0.1

Installation details:
Installed version: v4.2 - done  [Update available - v4.3](https://github.com/Tzahi12345/YoutubeDL-Material/releases/latest). You can update from the settings menu.

**Additional context**

Thanks for you project, I've downloaded 100GB youtube music video in 1 year ago.

**Comment by Tzahi12345** [comment]
Can you try pulling the newest `latest` or `nightly` image? I haven't tested the internal update button in a bit so that's why it's a bit broken.

**Comment by HxBreak** [comment]
@Tzahi12345 nightly version works fine, thinks

**Comment by HxBreak** [comment]
@Tzahi12345 By the way, May you tell me how to download all of youtube videos from someone, Example https://www.youtube.com/@divr

**Comment by Tzahi12345** [comment]
That user doesn't seem available to me, but generally you can go into the Subscriptions tab, hit the plus button, and paste in the link to subscribe. Any new uploads, it will also download automatically.
