### ISSUE TITLE
[BUG] Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by spiffzilla** [Tzahi12345/YoutubeDL-Material#894]
**Describe the bug**
Unable to start, 'ERR_STRING_TOO_LONG'
Error: Cannot create a string longer than 0x1fffffe8 characters
Running as a Docker under Unraid

**To Reproduce**
Install via Community apps,

**Expected behavior**
Program should start as it has for +1 year

**Environment**
- Last update in Unraid: May 3:rd
- tzahi12345/youtubedl-material

**Additional context**
Log (continues for a looong time):
2023-05-01T19:06:46: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-01T19:06:46: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-01T19:06:46: PM2 log: App [YoutubeDL-Material:0] online
2023-05-01T19:06:47: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-01T19:06:47: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-01T19:06:47: PM2 log: App [YoutubeDL-Material:0] online
2023-05-01T19:06:47: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-01T19:06:47: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-01T19:06:47: PM2 log: App [YoutubeDL-Material:0] online
2023-05-01T19:06:48: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-01T19:06:48: PM2 log: Script /app/app.js had too many unstable restarts (16). Stopped. "errored"
2023-05-01T19:06:49: PM2 log: 0 application online, retry = 3
2023-05-01T19:06:51: PM2 log: 0 application online, retry = 2
2023-05-01T19:06:53: PM2 log: 0 application online, retry = 1
2023-05-01T19:06:55: PM2 log: 0 application online, retry = 0
2023-05-01T19:06:55: PM2 log: [Watch] Stop watching YoutubeDL-Material
2023-05-01T19:06:55: PM2 log: Stopping app:YoutubeDL-Material id:0
2023-05-01T19:06:56: PM2 log: PM2 successfully stopped

> backend@1.0.0 start
> pm2-runtime --raw pm2.config.js

2023-05-05T19:40:44: PM2 log: Launching in no daemon mode
2023-05-05T19:40:44: PM2 log: [Watch] Start watching YoutubeDL-Material
2023-05-05T19:40:44: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-05T19:40:44: PM2 log: App [YoutubeDL-Material:0] online
2023-05-05T19:40:45: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-05T19:40:45: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-05T19:40:45: PM2 log: App [YoutubeDL-Material:0] online
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at readFileSync (node:fs:497:41)
    at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:35:22)
    at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
    at Object.<anonymous> (/app/db.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_STRING_TOO_LONG'
}
2023-05-05T19:40:46: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-05T19:40:46: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-05T19:40:46: PM2 log: App [YoutubeDL-Material:0] online
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at readFileSync (node:fs:497:41)
    at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:35:22)
    at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
    at Object.<anonymous> (/app/db.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_STRING_TOO_LONG'
}
2023-05-05T19:40:47: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-05T19:40:47: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-05T19:40:47: PM2 log: App [YoutubeDL-Material:0] online
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at readFileSync (node:fs:497:41)
    at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:35:22)
    at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
    at Object.<anonymous> (/app/db.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_STRING_TOO_LONG'
}
2023-05-05T19:40:48: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-05T19:40:48: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-05T19:40:48: PM2 log: App [YoutubeDL-Material:0] online
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at readFileSync (node:fs:497:41)
    at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:35:22)
    at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
    at Object.<anonymous> (/app/db.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_STRING_TOO_LONG'
}

**Comment by Tzahi12345** [comment]
Did you update before this started happening? I'm guessing you're not using MongoDB?

It looks like there's an issue reading the DB which is why I'm asking

**Comment by spiffzilla** [comment]
Thanks

I renamed my DB (local_db.json) wich was 524 MB and everything started to work..  so you were correct, broken DB
I wonder if it can be salvaged, tried it on jsonlint (online) to see how it looked but no luck.

Will a mongoDB help me to keep a sane DB? Hate to loose all of my archive

**Comment by Tzahi12345** [comment]
I can help you get it back, it will take a couple steps though. 

1. Firstly, yes, MongoDB is the way to go for a DB this big. Set that up first and confirm it's working by testing the connection string in the `Database` tab in the settings, and click `Transfer DB to MongoDB`
2. In `appdata` create a folder called `db_backup`
3. Copy your old (524MB) local_db.json into there and name it `local_db.json.1683320968.000.bak`
4. Go into your Tasks menu and click `Restore DB from backup`. If you don't see Tasks, you may need to add permissions to it by going into the `Users` tab and updating the admin role to have permissions for it. I'll fix this tonight so it'll have it by default
5. You should see your old DB. Click it and hit restore

If the DB isn't corrupt this should work, it may take a bit since your DB is so large but you'll notice everything is smoother with MongoDB. You can see more details about it here: https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Setting-a-MongoDB-backend-to-use-as-database-provider-for-YTDL-M

**Comment by spiffzilla** [comment]
Cool, thanks @Tzahi12345 will give it a shot tonight
I'll report back

**Comment by spiffzilla** [comment]
Not sure what "it takes a bit" actually is, have been restoring for 30 mins so far.
But if that's 'normal' i'm fine with that. Hopefully the process hasn't hung :-)

**Comment by GlassedSilver** [comment]
> Not sure what "it takes a bit" actually is, have been restoring for 60 mins so far. But if that's 'normal' i'm fine with that. Hopefully the process hasn't hung :-)

Don't remember how long my 32k entries db took, but it took a while. Feel free to inspect the db with mongo-express or adminer or something and see if the db contains about as many "documents" (entries) in the relevant table as you'd expect.

**Comment by spiffzilla** [comment]
I'll take a look in the db...   it's still says that it's loading :-)
![image](https://user-images.githubusercontent.com/3751145/236884024-1ab822b7-f3f2-4d90-b18a-b600212fb520.png)

**Comment by spiffzilla** [comment]
Looks like the DB is doing things at least, I'll let it run again and see if that changes...
![image](https://user-images.githubusercontent.com/3751145/236886682-54f2eaac-d5ff-4e01-85ba-9b272f2a3535.png)

**Comment by Tzahi12345** [comment]
You technically don't have to re-download everything as in the Tasks menu there's a task that will find missing DB records and reimport them.

In your case because users/subscriptions are missing it won't look for those files but if you resubscribe and then run the task, it will find them (given you recreate the users that the subscriptions belong to, if you use multi user mode). Here's some older instructions back when the task didn't exist and we just checked for the missing files at startup: https://github.com/Tzahi12345/YoutubeDL-Material/issues/210#issuecomment-687649272

I'm working on a PR to auto rebuild the DB to avoid this issue in the future. Still got some work to do so it'll be a few days before it hits the nightly but should make this kind of stuff smoother: #900 

Also made #896 so we can properly warn users when the local DB gets too large.

Sorry for the trouble! DB issues are annoying but it'll be a lot easier to deal with in the near future

**Comment by spiffzilla** [comment]
No problem at all, just happy to have to software. And I got pushed to start using Mongo, so in total it's a win ;-)
