### ISSUE TITLE
[BUG] Unable to run as docker in Rp4

### ISSUE THREAD

**Issue by boomramada** [Tzahi12345/YoutubeDL-Material#923]
**Describe the bug**

I'm trying to run as docker with the following command:

`
DOCKER_CONFIGS=$(pwd)

docker run -d --init --name=youtube-dl \
  -e ALLOW_CONFIG_MUTATIONS=true \
  -e ytdl_mongodb_connection_string=mongodb://ytdl-mongo-db:27017 \
  -e ytdl_use_local_db=false \
  -e write_ytdl_config=true \
  -v "$DOCKER_CONFIGS/appdata:/app/appdata" \
  -v "$DOCKER_CONFIGS/audio:/app/audio" \
  -v "$DOCKER_CONFIGS/video:/app/video" \
  -v "$DOCKER_CONFIGS/subscriptions:/app/subscriptions" \
  -v "$DOCKER_CONFIGS/users:/app/users" \
  -p 8998:17442 \
  --restart=unless-stopped \
  tzahi12345/youtubedl-material:latest
`

and getting the following error at the start-up

2023-05-23T07:12:48: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-23T07:12:48: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-23T07:12:48: PM2 log: App [YoutubeDL-Material:0] online
Error: EACCES: permission denied, mkdir 'appdata/logs'
    at Object.mkdirSync (node:fs:1336:3)
    at File._createLogDirIfNotExist (/app/node_modules/winston/lib/winston/transports/file.js:691:10)
    at new File (/app/node_modules/winston/lib/winston/transports/file.js:92:28)
    at Object.<anonymous> (/app/logger.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: 'appdata/logs'
}
2023-05-23T07:12:48: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
2023-05-23T07:12:48: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2023-05-23T07:12:48: PM2 log: App [YoutubeDL-Material:0] online

**Comment by boomramada** [comment]
I found the issue, docker folders are created under wrong group and user policy.

**Comment by Tzahi12345** [comment]
Should be resolved in the latest nightly
