### ISSUE TITLE
[BUG] Fails to download my music playlist

### ISSUE THREAD

**Issue by Gaffers2277** [Tzahi12345/YoutubeDL-Material#927]
**Describe the bug**
I have a Public Mixes Playlist i want to backup as videos have been deleted over time. I added it as a subscription playlist but when YT-Material tries to look at it and download it fails. Im not sure why, i have my cookies set and it works for channels as i have already downloaded some.

**To Reproduce**
1. Go to Add Playlist
2. It starts to parse
3. See errors in log 

**Expected behavior**
Downloads available videos as audio files 

**Environment**
Installation details:

Installed version: v4.3.1 - You are up to date.

Installation type: docker
Docker tag: latest
Commit hash: 80b41af
Build date: 2023-05-19 

**Logs**
2023-05-25T00:04:05.352Z ERROR: WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-sigfuncs/js_41b8bed0_102.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-sigfuncs/js_41b8bed0_106.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

ERROR: [youtube] amysBy-1utM: Video unavailable. This video is private
ERROR: [youtube] z7c4hG60UYM: Video unavailable. This video is private
ERROR: [youtube] cQ-a18zEBmI: Video unavailable. This video has been removed by the uploader
WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

ERROR: [youtube] jNE2Yi_IQ48: Video unavailable. This video is not available
WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

ERROR: [youtube] aylxPWZOsDo: Video unavailable. This video contains content from SME, who has blocked it in your country on copyright grounds
WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

ERROR: [youtube] dza_frgrujw: Video unavailable. This video is not available
WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

ERROR: [youtube] YoYB3x81V_c: Video unavailable. This video is no longer available due to a copyright claim by Bungie, Inc.
WARNING: Writing cache to '/root/.cache/yt-dlp/youtube-nsig/41b8bed0.json' failed: Traceback (most recent call last):
  File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
    os.makedirs(os.path.dirname(fn), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

2023-05-25T00:04:05.353Z ERROR: Subscription check failed!

**Comment by Tzahi12345** [comment]
Can you try on the latest nightly? I believe this is fixed

**Comment by Gaffers2277** [comment]
yeah, i'll give it a go

**Comment by Tzahi12345** [comment]
Should be resolved now in the latest tag, if not let me know and I'll re-open this issue.
