### ISSUE TITLE
[BUG] Can't subscribe / download bigger YouTube channel (RangeError)

### ISSUE THREAD

**Issue by Doublemyst** [Tzahi12345/YoutubeDL-Material#970]
**Describe the bug**
When trying to add a subscription to a channel with 1.4k videos, it seems to load endlessly, without showing the videos on the chanel / getting a possibility to download them.

**To Reproduce**
1. Go to Subscription
2. Click on "Add subscription"
3. Add this URL: https://www.youtube.com/@marcelpaa/
4. Select as Quality 720p
5. Click subscribe
6. See error from the logs

**Error from Logs**
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at FileSync.stringify [as serialize] (/app/node_modules/lowdb/adapters/_stringify.js:5:15)
    at FileSync.write (/app/node_modules/lowdb/adapters/FileSync.js:53:42)
    at LodashWrapper.db.write (/app/node_modules/lowdb/lib/main.js:37:21)
    at LodashWrapper.<anonymous> (/app/node_modules/lowdb/lib/main.js:19:15)
    at apply (/app/node_modules/lodash/lodash.js:488:27)
    at LodashWrapper.wrapper [as write] (/app/node_modules/lodash/lodash.js:5379:16)
    at Object.exports.insertRecordIntoTable (/app/db.js:255:39)
    at /app/subscriptions.js:36:22

**Expected behavior**
The videos on the channel should be shown, and it should be possible to download them.

**Environment**
OS: Unraid
Installed version: v4.3.2 -
Installation type: docker
Docker tag: latest
Commit hash: 13a03a7
Build date: 2023-05-27

**Comment by SickProdigy** [comment]
Think this one is similar:
#676
